spring.application.name=NoSqlLab1

spring.datasource.url=jdbc:postgresql://localhost:2222/postgres
spring.datasource.username=postgres
spring.datasource.password=hkmp5sd6
spring.jpa.hibernate.ddl-auto=update